sudo: required
dist: trusty
language: php
php:
  - 7.1
before_script:
  - phpenv config-rm xdebug.ini
  - pecl install ast-0.1.7
  - composer install --no-scripts --no-suggest
  - vendor/bin/phpcs --config-set installed_paths vendor/nocworx/phpcs/
script:
  - composer tests:phpcs
  - composer tests:phan
  - composer tests:unit
  - composer tests:integration
